### ISSUE TITLE
EE 2.2 compatibility : type error for data in Smile\ElasticsuiteCms\Model\Page\Indexer\Fulltext constructor

### ISSUE THREAD

**Issue by rbayet** [Smile-SA/module-elasticsuite-cms-search#10]
### Preconditions

Magento Version : 2.2.2

ElasticSuite Version : 2.5.2

ElasticSuite CMS Search Version : 2.1.2

Environment : Developer and Production

### Steps to reproduce
1. Wait for cron:run to perform a diff reindex of CMS pages

### Expected result
1. No specific error message in logs

### Actual result
In Production mode (Magento Cloud) /var/log/cron.log 
```
[2018-02-23 14:03:01.451084] Launching command 'php bin/magento cron:run && php bin/magento cron:run'.

Ran jobs by schedule.
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to Smile\ElasticsuiteCms\Model\Page\Indexer\Fulltext::__construct() must be of the type array, null given, called in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /app/vendor/smile/module-elasticsuite-cms-search/Model/Page/Indexer/Fulltext.php:66
Stack trace:
#0 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Smile\ElasticsuiteCms\Model\Page\Indexer\Fulltext->__construct(Object(Smile\ElasticsuiteCms\Model\Page\Indexer\Fulltext\Action\Full), Object(Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler), Object(Magento\Store\Model\StoreManager\Interceptor), Object(Magento\Framework\Search\Request\DimensionFactory), NULL)
#1 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Smile\\Elasticsu...', Array)
#2 /app/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\F in /app/vendor/smile/module-elasticsuite-cms-search/Model/Page/Indexer/Fulltext.php on line 66
```

In Developer mode (local environment) in [magento]/var/log/exception.log
```
[2018-02-23 10:36:04] report.CRITICAL: Missing required argument $data of Smile\ElasticsuiteCms\Model\Page\Indexer\Fulltext. {"exception":"[object] (BadMethodCallException(code: 0): Missing required argument $data of Smile\\ElasticsuiteCms\\Model\\Page\\Indexer\\Fulltext. at /var/www/mustela-dev/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:222)"} []
```

**Comment by rbayet** [comment]
As a side note : 
- the error is shown when running cron:run EVEN IF the index is in "update on save" (go figure ...)
- whatever the index configuration is and even if trying to silence the error by adding a "`= []`" (a default value to `array $data`), it looks like incremental reindexing does not work at all

Regards
Richard.

**Comment by romainruaud** [comment]
Yep, there was many mess to clean up here : 

- `$data` attribute had no purpose at all and has been removed.
- `mview` file was not listening to the `cms_page` table modifications, so this was useless.

I also fixed the `Update on Save` plugin that was not triggered since Magento 2.1 and their usage of Entity Manager.

Please update to latest 2.1.4 version to benefit these fixes.

Regards
