### ISSUE TITLE
Module enabled, but don't get any CMS pages in results

### ISSUE THREAD

**Issue by amenk** [Smile-SA/module-elasticsuite-cms-search#12]
![problem](https://user-images.githubusercontent.com/1087128/45082840-8e450280-b0fa-11e8-8b08-0a96fe63c711.png)
I installed and enabled dev-master, elasticsuite is 2.6.x-dev
But in autocomplete I do not get any results with CMS pages.
Indexes are completely rebuilt including
Elasticsuite Cms Page Indexing index has been rebuilt successfully in 00:00:01

Cms Page Autocomplete in the backend is set to 5 items.

**Comment by Fdec** [comment]
Hi amenk 

Have you look at your index and check if you have a cms index ? 

Your CMS pages are searchable ? Option "is_searchable" Yes/No on cms page edit in backoffice magento. 

Regards,

**Comment by amenk** [comment]
I did not change any is_searchable - so this really might be the case

**Comment by Fdec** [comment]
Hi amenk

Is it ok for you ?

**Comment by Fdec** [comment]
No response, so I close it.
