### ISSUE TITLE
error in indexer with CMS

### ISSUE THREAD

**Issue by brmor** [Smile-SA/module-elasticsuite-cms-search#15]
Hi, 

We have an issue with indexer Elasticsuite Cms Page.
see stack trace:

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php on line 206 and defined in /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php:172
Stack trace:
#0 /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php(206): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('widget_recently...', NULL)
#1 /var/www/project/vendor/magento/module-ui/Model/UiComponentGenerator.php(63): Magento\Framework\View\Element\UiComponentFactory->create('widget_recently...', NULL, Array)
#2 /var/www/project/vendor/magento/module-ui/Block/Wrapper.php(92): Magento\Ui\Model\UiComponentGenerator->generateUiComponent('widget_recently...', Object(Magento\Framework\View\Layout\Interceptor))
#3 /var/www/project/vendor/magento/module-catalog/view/frontend/templates/product in /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php on line 172

Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php on line 206 and defined in /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php on line 172

TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php on line 206 in /var/www/project/vendor/magento/framework/View/Element/UiComponentFactory.php on line 172

Call Stack:
    0.0001     351768   1. {main}() /var/www/project/bin/magento:0
    0.3926   27346456   2. Symfony\Component\Console\Application->run() /var/www/project/bin/magento:23
    0.3953   27792952   3. Magento\Framework\Console\Cli->doRun() /var/www/project/vendor/symfony/console/Application.php:117
    0.3953   27792952   4. Symfony\Component\Console\Application->doRun() /var/www/project/vendor/magento/framework/Console/Cli.php:104
    0.9259   43213240   5. Symfony\Component\Console\Application->doRunCommand() /var/www/project/vendor/symfony/console/Application.php:185
    0.9260   43213240   6. Symfony\Component\Console\Command\Command->run() /var/www/project/vendor/symfony/console/Application.php:835
    0.9262   43218664   7. Magento\Indexer\Console\Command\IndexerReindexCommand->execute() /var/www/project/vendor/symfony/console/Command/Command.php:245
    1.0431   52017624   8. Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll() /var/www/project/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php:86
    1.0431   52017624   9. Magento\Indexer\Model\Indexer\Interceptor->reindexAll() /var/www/project/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:248
    1.0431   52017624  10. Magento\Indexer\Model\Indexer->reindexAll() /var/www/project/generated/code/Magento/Indexer/Model/Indexer/Interceptor.php:323

I've put a widget in content to cms Page.
So, when I delete widget, Indexation has been successfull

**Comment by Fdec** [comment]
Hi @brmor 
Is it still relevant ?
