### ISSUE TITLE
Erreur class Fulltext/Select  not found

### ISSUE THREAD

**Issue by brmor** [Smile-SA/module-elasticsuite-cms-search#16]
dans la class module-elasticsuite-cms-search/Model/ResourceModel/Page/Fulltext/Collection.php

ligne 125     public function setOrder($attribute, $dir = Select::SQL_DESC) Select n'est pas déclarer...

**Comment by loiczam** [comment]
Un PR est en attente de validation https://github.com/Smile-SA/module-elasticsuite-cms-search/pull/17
