### ISSUE TITLE
Disabled pages are visible in search result

### ISSUE THREAD

**Issue by evilprophet** [Smile-SA/module-elasticsuite-cms-search#18]
### Preconditions
Magento Version : 2.2.5

ElasticSuite Version : 2.6.6

ElasticSuite CMS Search Version : 2.2.1

### Steps to reproduce
1. Add 2 pages, one with status enabled, second with disabled.
![image](https://user-images.githubusercontent.com/9113198/52944457-b86c4300-336f-11e9-91a3-23dd45cfe47d.png)

### Expected result
1. A disabled page shouldn't be visible.
![image](https://user-images.githubusercontent.com/9113198/52944606-1731bc80-3370-11e9-89b1-130b774d0691.png)

### Actual result
1. A disabled page is visible.
![image](https://user-images.githubusercontent.com/9113198/52944515-d5a11180-336f-11e9-8a67-46de14d483d7.png)

**Comment by romainruaud** [comment]
Merged.

New minor release published.

Regards
