### ISSUE TITLE
Fatal Error Occured 

### ISSUE THREAD

**Issue by Moinashraf** [Smile-SA/module-elasticsuite-cms-search#2]
Fatal error:  Class 'Smile\ElasticsuiteCms\Helper\AbstractConfiguration' not found in /var/www/html/mage/app/code/Smile/ElasticsuiteCms/Helper/Configuration.php on line 27

**Comment by romainruaud** [comment]
This is because you did not install [elasticsuite](https://github.com/Smile-SA/elasticsuite) previously.

Maybe you installed this module directly via tar.gz. The only acceptable way to install it is via composer by running : `composer require smile/module-elasticsuite-cms-search`
