### ISSUE TITLE
No result on multiple websites or stores 

### ISSUE THREAD

**Issue by ihor-ivchenko** [Smile-SA/module-elasticsuite-cms-search#21]
### **Preconditions**

Magento Cloud: 2.2.6

Elasticsearch: 5.2

ElasticSuite CMS Search Version: 2.1.4

### **Steps to reproduce**

1. Magento with multiple websites or stores 
2. Create cms pages to different stores
3. 'Is searchable' is enabled on each page.
4. Make full reindex
5. Go to any storefront and use the search bar

### **Expected result**
The result page with found items.

### **Actual result**
Zero search results

The same configuration but with only one store works fine. Is it a bug or need to do some settings?

**Comment by Fdec** [comment]
Hi @blotted 

Have you find a solution? If yes, can you propose a PR ? Thanks

**Comment by Fdec** [comment]
Closed because non reproductable
