### ISSUE TITLE
Any hints for getting CMS results?

### ISSUE THREAD

**Issue by casconed** [Smile-SA/module-elasticsuite-cms-search#3]
I realize this module may be somewhat unsupported but I was able to install it, and it reports that CMS pages are getting indexed. However I don't see any CMS results in the autocomplete. Any suggestions to get this working?

**Comment by netdrag** [comment]
Be sure to set the "is searchable" flag when you create/edit your CMS pages

**Comment by romainruaud** [comment]
@netdrag answer is the proper one. You have to set `is_searchable=1` to the pages you want to be indexed in the search engine.

I close the issue for being answered and now far outdated.
