### ISSUE TITLE
Cannot disable the autocomplete results

### ISSUE THREAD

**Issue by stb** [Smile-SA/module-elasticsuite-cms-search#33]
### Preconditions

Magento Version : 2.3.4

Module Elasticsuite Cms Search Version : 2.2.7

Environment : Developer

### Steps to reproduce

1. Set Autocomplete Max Size to 0

### Expected result

1. No Autocomplete results

### Actual result

1. Still shows results

**Comment by rbayet** [comment]
Fixed by PR #34 available in release 2.2.8
