### ISSUE TITLE
Behavioral Oprimizers

### ISSUE THREAD

**Issue by qbo-tech** [Smile-SA/module-elasticsuite-cms-search#37]
Hi, 
First of all, thanks and congrats for you GREAT work.

This is not a issue, but rather a roadmap question.

When do you guys think Behavioral Oprimizers will be ready ?

Im working on version 2.9 but i dont see anywhere on the Optimizers config nor in documentation about this, just a mention on the docs that it was part of last year's roadmap.

Let me know if you have any updates on this, please.

**Comment by romainruaud** [comment]
Hi @qbo-tech 

Please get in touch with us directly by mail at elasticsuite@smile.fr to discuss about this topic, we have huge things to share with you :)
