### ISSUE TITLE
CMS pages are not removed from search autocomplete when "is_searchable" flag is turned off, or even when page is disabled

### ISSUE THREAD

**Issue by emelezhik** [Smile-SA/module-elasticsuite-cms-search#39]
CMS pages are not removed from search autocomplete when "is_searchable" flag is turned off, or even when page is disabled

### Preconditions
Magento Cloud
Magento Version : Magento Cloud 2.4.3-p1
Module Elasticsuite Cms Search Version : "smile/module-elasticsuite-cms-search": "^2.2"
Environment : Production
Third party modules : Elasticsearch enabled

### Steps to reproduce
1. Enable search autocomplete for CMS pages
2. Add some test CMS page, enable it, make toggle "is_searchable" to be enabled.
3. Check that this page is visible in search autocomplete suggestions
4. Put toggle to disabled and save page
5. Check for this page in search autocomplete suggestions again

### Expected result
1. CMS page should not be shown in search autocomplete suggestions now

### Actual result
1. It does, and is removed from autocomplete suggestions only after full reindex

### Explanations why this happens
Mechanics is as follows.

- during search request, this module first requests CMS page ids from Elastic which match search query, and thereafter loads full pages data from MySql;
- only is_searchable = true CMS pages are to be included into search results, but this check is performed not by means of MySql request. Seems it is performed by requesting pages from Elastic and assuming that Elastic contains only is_searchable pages;
- module has separate indexer to process CMS page saves and reindex them in Elastic, for single pages this is method Smile\ElasticsuiteCms\Model\Page\Indexer\Fulltext::execute;
- - as a side note, full reindex leads to removal and re-creation of whole index in Elastic, that's why it helps to resolve observable cases.

Thus finally,
- Reindexer for single CMS pages saving, is triggered when CMS page is saved with is_searchable = true, but is not triggered when page is saved with is_searchable = false. As a result, data for this page is not removed from Elastic index specifically in the case when we disable is_searchable attribute, and we observe the behavior as described in the ticket.

I've tested this in Update On Save indexer mode both on local RedArc, and fresh M2.4.3 install with smile/elasticsuite and smile/module-elasticsuite-cms-search modules.

### How to fix
Remove this check:
- Plugin/Indexer/Page/Save/ReindexPageAfterSave.php :: 58
which runs reindex only if ($page->getIsSearchable())

and reindex CMS page for all cases when it is saved.

**Comment by romainruaud** [comment]
Fixed in https://github.com/Smile-SA/magento2-module-elasticsuite-cms-search/commit/f25e3c8c261b21e864bf9263878f8111eb1e9e26
