### ISSUE TITLE
Index of CMS PAges 0

### ISSUE THREAD

**Issue by rimmeh8** [Smile-SA/module-elasticsuite-cms-search#40]
### Preconditions

Magento Version : 2.4.2

Module Elasticsuite Cms Search Version :  latest 2.1

Environment : dev at php 7.4.x

Third party modules : 

### Steps to reproduce

1. install cms search plugin
2. reindex cms index
3. CMS Index stays at 0

### Expected result

1. CMS Pages gets Indexed

### Actual result

1.  The Index of CMS PAges stays at Zero

**Comment by romainruaud** [comment]
@rimmeh8 you have to set "is searchable = yes" to the pages your want to get indexed. By default, no pages are indexed.

Regards
