### ISSUE TITLE
Fulltext Action throws 'Incorrect theme identification key' when full reindex is triggered via data patch

### ISSUE THREAD

**Issue by z4kko** [Smile-SA/module-elasticsuite-cms-search#41]
The fulltext action model tries to load the 'design' from the frontend area, while not emulating said area.

### Preconditions
- Vanilla Magento CE 2.4.5
- smile/module-elasticsuite-cms-search@2.2.8
- Module `magento/module-configurable-sample-data` was installed
- bin/magento setup:upgrade is invoked, but stops at `\Magento\ConfigurableSampleData\Setup\RecurringData`, which is triggering a full system reindex

Environment : developer mode

Third party modules :
- smile/elasticsuite@2.10.11

### Steps to reproduce
- Install sample data via composer
- Install smile/module-elasticsuite-cms-search@2.2.8 via composer
- Trigger `bin/magento setup:upgrade`

### Expected result
`setup:upgrade` works without exceptions.

### Actual result
`setup:upgrade` throws an exception at `vendor/magento/framework/View/Design/Theme/FlyweightFactory.php:62`.

**Comment by romainruaud** [comment]
I close, this was already fixed but for strange reasons it was never delivered into 2.2.9 tag.

Recent versions (2.10.x and 2.11.x) are including the fix.

Feel free to open a new issue and PR if needed.

regards
