### ISSUE TITLE
Elasticsuite Cms Page Indexing index process error during indexation process: Cannot instantiate interface Magento\Framework\Indexer\SaveHandler\IndexerInterface

### ISSUE THREAD

**Issue by emirajbbd** [Smile-SA/module-elasticsuite-cms-search#44]
Preconditions

    Vanilla Magento EE 2.4.5-p1
    smile/module-elasticsuite-cms-search@2.2.8
    PHP:8.1
    

Environment : production mode
Third party modules : amasty/blog

### Steps to reproduce

1. Install smile/module-elasticsuite-cms-search@2.2.8 via composer
2.Trigger bin/magento indexer:reindex

### Expected result

1. indexer:reindex: works without exceptions.

### Actual result

1. Elasticsuite Cms Page Indexing index process error during indexation process:
Cannot instantiate interface Magento\Framework\Indexer\SaveHandler\IndexerInterface

**Comment by richardechidna** [comment]
Any update on this?

**Comment by romainruaud** [comment]
Hi, I am not able to reproduce this on legacy install.

However, I'm not using amasty/blog module so this might be due to this module being uncompatible. Since this is a paid module, I suggest you to reach Amasty support.

Regards
