### ISSUE TITLE
No class named Smile\ElasticsuiteCms\Model\ResourceModel\Page\Fulltext\CollectionFactory

### ISSUE THREAD

**Issue by cioroianudenis** [Smile-SA/module-elasticsuite-cms-search#45]
I get the following error on Magento 2.4
`main.CRITICAL: Impossible to process constructor argument Parameter #3 [ <required> Smile\ElasticsuiteCms\Model\ResourceModel\Page\Fulltext\CollectionFactory $cmsCollectionFactory ] of Smile\ElasticsuiteCms\Model\Autocomplete\Page\DataProvider class {"report_id":"3449cb9ecbfdcdd7175659c4a2603f22b849175613319db251045f179e64b1ed","exception":"[object] (ReflectionException(code: 0): Impossible to process constructor argument Parameter #3 [ <required> Smile\\ElasticsuiteCms\\Model\\ResourceModel\\Page\\Fulltext\\CollectionFactory $cmsCollectionFactory ] of Smile\\ElasticsuiteCms\\Model\\Autocomplete\\Page\\DataProvider class at /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:45, ReflectionException(code: 0): Class Smile\\ElasticsuiteCms\\Model\\ResourceModel\\Page\\Fulltext\\CollectionFactory does not exist at /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:34)"} []`
and after some digging through the code, in `Model/Auotocomplete/Page/DataProvider.php` at the line that says use `Smile\ElasticsuiteCms\Model\ResourceModel\Page\Fulltext\CollectionFactory as CmsCollectionFactory;` there is no class named "`CollectionFactory`" under "`Smile\ElasticsuiteCms\Model\ResourceModel\Page\Fulltext`" namespace

**Comment by romainruaud** [comment]
Hi @cioroianudenis the Factory classes are supposed to be autogenerated by Magento.

I am not able to reproduce your issue.

Best regards
