### ISSUE TITLE
Performance issues SWAT Report - triggers

### ISSUE THREAD

**Issue by Leszek-mediawave** [Smile-SA/module-elasticsuite-cms-search#46]
Magento SWAT Report is showing multiple issues with performance of smile modules

### Preconditions
we are using magento cloud infrastructure

Magento Version : magento 2.4.4-p2 EE

Module Elasticsuite Cms Search Version :smile/module-elasticsuite-cms-search: 2.2.8

Environment : Dev, Stage, Live

Third party modules : multiple third party modules, and elasticsuite related:
"smile/elasticsuite":2.10.12.1
"smile/module-elasticsuite-ems-search": 2.2.8
"smile/module-elasticsuite-quick-order": 2.10.1
"smile/module-elasticsuite-rating": 2.3.0
"web200/magento-elasticsuite-ajax":  v0.8.4

### Steps to reproduce

1. we executed SWAT report (Site-Wide Analysis Tool) and we got hints about performance

### Expected result

1. No performance issues in SWAT Report

### Actual result

1. ![image](https://user-images.githubusercontent.com/66359726/234825412-a8bd834c-f0da-4e45-86ff-cf2dabc0f444.png)

we contacted magento support and they answered:
"On investigation we found that trigger usage is because of the below 3rd party module. module-elasticsuite-cms-search
 
grep -iR 'cms_page' vendor/
vendor/smile/module-elasticsuite-cms-search/etc/mview.xml:            <table name="cms_page" entity_column="page_id" />" 

Triggers are used to log changes into audit tables. The following list of added triggers was found in the MySQL database.

TRIGGER_NAME | TRIGGER_TABLE
trg_cms_page_after_insert | cms_page
trg_cms_page_after_update | cms_page
trg_cms_page_after_delete | cms_page
trg_smile_virtualctgr_cat_ctgr_prd_position_after_insert | smile_virtualcategory_catalog_category_product_position
trg_smile_virtualctgr_cat_ctgr_prd_position_after_update | smile_virtualcategory_catalog_category_product_position
trg_smile_virtualctgr_cat_ctgr_prd_position_after_delete | smile_virtualcategory_catalog_category_product_position

Recommendation
To avoid issues with triggers negatively impacting performance follow these best practices:

For custom triggers that write some data when the trigger is executed, move this logic to write directly to the audit tables instead. For example, add an additional query in the application code, after the query, for the custom trigger.
Review existing custom triggers and consider removing them and writing directly to the tables from the application side. Check for existing triggers in the database by following steps in [Show Triggers](https://dev.mysql.com/doc/refman/8.0/en/show-triggers.html).

**Comment by romainruaud** [comment]
Hi, we will not fix this.

We implement the reindexing of Cms pages with an mview.xml file because it's the best way to handle this.

Those triggers are unlikely to cause any performance issue.

You can consider this as a false positive.

regards
