### ISSUE TITLE
Require dependency issue when upgrading smile/elasticsuite to version ~2.11.0

### ISSUE THREAD

**Issue by ymoudouani** [Smile-SA/module-elasticsuite-cms-search#47]
Require dependency issue when upgrading smile/elasticsuite to version ~2.11.0

### Preconditions

Magento Commerce Cloud Version : 2.4.6-p3

Module Elasticsuite Cms Search Version :

Environment : Developer

Third party modules :
- smile/elasticsuite
- smile/module-elasticsuite-cms-search
- smile/module-elasticsuite-quick-order

### Steps to reproduce

1.Running composer require smile/elasticsuite ~2.11.0 and having dependency with smile/module-elasticsuite-cms-search

### Expected result

1. composer require smile/elasticsuite ~2.11.0 should run successfully 

### Actual result

Problem 1
    - Root composer.json requires smile/elasticsuite ~2.11.0, found smile/elasticsuite[2.11.0, 2.11.1, 2.11.1.1, 2.11.2, 2.11.3, 2.11.3.1, 2.11.3.2, 2.11.3.3, 2.11.4, 2.11.4.1] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - smile/module-custom-entity-product-link is locked to version dev-release-v2.6.4 and an update of this package was not requested.
    - smile/module-custom-entity-product-link dev-release-v2.6.4 requires smile/elasticsuite ^2.8.0 -> found smile/elasticsuite[2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.8.10, 2.8.11, 2.8.12, 2.8.13, 2.8.14, 2.8.15, 2.8.15.1, 2.8.16, 2.8.16.1, 2.8.17, 2.8.18, 2.8.19, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5-rc1, 2.9.5, 2.9.6, 2.9.7, 2.9.8, 2.9.9, 2.9.9.1, 2.9.10, 2.9.10.1, 2.9.11, 2.9.12, 2.9.13, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4-rc1, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 2.10.8, 2.10.8.1, 2.10.9, 2.10.9.1, 2.10.10, 2.10.11, 2.10.12, 2.10.12.1, 2.10.13, 2.10.13.1, 2.10.13.2, 2.10.13.3, 2.10.14, 2.10.15, 2.10.15.1, 2.10.16, 2.10.17, 2.10.17.1, 2.10.17.2, 2.10.17.3, 2.10.18, 2.10.18.1, 2.11.0, 2.11.1, 2.11.1.1, 2.11.2, 2.11.3, 2.11.3.1, 2.11.3.2, 2.11.3.3, 2.11.4, 2.11.4.1] but these were not loaded, likely because it conflicts with another require.
  Problem 3
    - smile/module-elasticsuite-cms-search is locked to version 2.2.8 and an update of this package was not requested.
    - smile/module-elasticsuite-cms-search 2.2.8 requires smile/elasticsuite ^2.6.0 -> found smile/elasticsuite[2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.8.10, 2.8.11, 2.8.12, 2.8.13, 2.8.14, 2.8.15, 2.8.15.1, 2.8.16, 2.8.16.1, 2.8.17, 2.8.18, 2.8.19, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5-rc1, 2.9.5, 2.9.6, 2.9.7, 2.9.8, 2.9.9, 2.9.9.1, 2.9.10, 2.9.10.1, 2.9.11, 2.9.12, 2.9.13, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4-rc1, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 2.10.8, 2.10.8.1, 2.10.9, 2.10.9.1, 2.10.10, 2.10.11, 2.10.12, 2.10.12.1, 2.10.13, 2.10.13.1, 2.10.13.2, 2.10.13.3, 2.10.14, 2.10.15, 2.10.15.1, 2.10.16, 2.10.17, 2.10.17.1, 2.10.17.2, 2.10.17.3, 2.10.18, 2.10.18.1, 2.11.0, 2.11.1, 2.11.1.1, 2.11.2, 2.11.3, 2.11.3.1, 2.11.3.2, 2.11.3.3, 2.11.4, 2.11.4.1] but these were not loaded, likely because it conflicts with another require.
  Problem 4
    - smile/module-elasticsuite-quick-order is locked to version 2.10.1 and an update of this package was not requested.
    - smile/module-elasticsuite-quick-order 2.10.1 requires smile/elasticsuite ~2.10.0 -> found smile/elasticsuite[2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4-rc1, 2.10.4, 2.10.5, 2.10.6, 2.10.7, 2.10.8, 2.10.8.1, 2.10.9, 2.10.9.1, 2.10.10, 2.10.11, 2.10.12, 2.10.12.1, 2.10.13, 2.10.13.1, 2.10.13.2, 2.10.13.3, 2.10.14, 2.10.15, 2.10.15.1, 2.10.16, 2.10.17, 2.10.17.1, 2.10.17.2, 2.10.17.3, 2.10.18, 2.10.18.1] but it conflicts with your root composer.json require (~2.11.0).

**Comment by romainruaud** [comment]
Hi, this should be fixed with the new version policy of this module.

Regards
